from django.db import models
from django.utils import timezone
import datetime # Import datetime

# Catálogos primero ya que otras tablas dependen de ellos

class CrowdUsuarioNivel(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito en Django)
    nombre = models.CharField(max_length=255, verbose_name="Nombre del Nivel")
    color = models.CharField(max_length=255, verbose_name="Color") # Asumo que es un código hexadecimal o nombre de color
    icono_path = models.TextField(verbose_name="Ruta del Icono")
    activo = models.BooleanField(default=True, verbose_name="Activo")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Nivel de Usuario"
        verbose_name_plural = "Niveles de Usuario"

class CrowdCatalogoUsuarioTipo(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito en Django)
    nombre = models.CharField(max_length=255, null=True, blank=True, verbose_name="Nombre del Tipo de Usuario") # SQL dice varchar, no NOT NULL
    activo = models.BooleanField(default=True, null=True, blank=True, verbose_name="Activo") # SQL dice boolean

    def __str__(self):
        return self.nombre or f"Tipo ID: {self.id}"

    class Meta:
        verbose_name = "Tipo de Usuario (Catálogo)"
        verbose_name_plural = "Tipos de Usuario (Catálogo)"

class CrowdUsuario(models.Model):
    id_morelia = models.CharField(max_length=255, unique=True, primary_key=True, verbose_name="ID Morelia")
    email = models.EmailField(max_length=255, verbose_name="Correo Electrónico") # Django usa EmailField para varchar que son emails
    password = models.CharField(max_length=255, verbose_name="Contraseña") # Se debe manejar el hashing de contraseñas
    first_name = models.CharField(max_length=255, verbose_name="Nombres")
    last_name = models.CharField(max_length=255, verbose_name="Apellidos")

    usuario_tipo = models.ForeignKey(
        CrowdCatalogoUsuarioTipo,
        on_delete=models.SET_NULL, # O models.PROTECT si no se deben borrar tipos con usuarios asignados
        null=True, blank=True, # SQL dice int, no NOT NULL
        verbose_name="Tipo de Usuario"
    )
    fecha_creacion = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Creación")

    nivel = models.ForeignKey(
        CrowdUsuarioNivel,
        on_delete=models.SET_NULL, # O models.PROTECT
        null=True, blank=True, # SQL dice int, no NOT NULL
        verbose_name="Nivel"
    )
    activo = models.BooleanField(default=True, null=True, blank=True, verbose_name="Activo") # SQL dice bool

    # Campos relacionados con Django Auth User (si se decide integrar/heredar más adelante)
    # is_staff, is_active, is_superuser, last_login, date_joined (este último similar a fecha_creacion)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.id_morelia})"

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

class CrowdCategoria(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    nombre = models.CharField(max_length=255, verbose_name="Nombre de la Categoría")
    descripcion = models.CharField(max_length=255, null=True, blank=True, verbose_name="Descripción") # SQL dice varchar, no text
    activo = models.BooleanField(default=True, null=True, blank=True, verbose_name="Activo") # SQL dice bool

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Categoría de Caso"
        verbose_name_plural = "Categorías de Casos"

class CrowdCatalogoEstatus(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    nombre = models.CharField(max_length=255, null=True, blank=True, verbose_name="Nombre del Estatus") # SQL dice varchar
    activo = models.BooleanField(default=True, null=True, blank=True, verbose_name="Activo") # SQL dice boolean

    def __str__(self):
        return self.nombre or f"Estatus ID: {self.id}"

    class Meta:
        verbose_name = "Estatus (Catálogo)"
        verbose_name_plural = "Estatus (Catálogo)"

class SistemaMunicipalPrograma(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    descripcion_nombre = models.TextField(null=True, blank=True, verbose_name="Nombre Descriptivo del Programa")
    descripcion_detalles = models.TextField(null=True, blank=True, verbose_name="Detalles Descriptivos del Programa")
    presupuesto_total = models.FloatField(null=True, blank=True, verbose_name="Presupuesto Total")
    presupuesto_disponible = models.FloatField(null=True, blank=True, verbose_name="Presupuesto Disponible")
    presupuesto_meta = models.FloatField(null=True, blank=True, verbose_name="Presupuesto Meta")
    # "estatus" char NOT NULL - Asumiré longitudes cortas para CharField, o podría ser un ChoiceField
    ESTATUS_CHOICES = [
        ('A', 'Activo'), # Ejemplo, definir los char reales
        ('I', 'Inactivo'),
        ('C', 'Completado'),
        ('P', 'Pendiente'),
    ]
    estatus = models.CharField(max_length=1, choices=ESTATUS_CHOICES, verbose_name="Estatus del Programa")
    fecha_inicio = models.DateField(null=True, blank=True, verbose_name="Fecha de Inicio")
    fecha_fin = models.DateField(null=True, blank=True, verbose_name="Fecha de Fin")
    cuenta_bancaria = models.CharField(max_length=255, null=True, blank=True, verbose_name="Cuenta Bancaria")

    def __str__(self):
        return self.descripcion_nombre or f"Programa ID: {self.id}"

    class Meta:
        verbose_name = "Programa Municipal"
        verbose_name_plural = "Programas Municipales"

class Factura(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    datos = models.TextField(null=True, blank=True, verbose_name="Datos de la Factura") # Asumo que es un JSON o XML como texto
    id_empresa = models.ForeignKey(
        CrowdUsuario,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='facturas_emitidas', # Asumiendo que un usuario puede ser empresa
        verbose_name="ID de Empresa (Usuario)"
    )
    id_ciudadano = models.ForeignKey(
        CrowdUsuario,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='facturas_recibidas',
        verbose_name="ID de Ciudadano (Usuario)"
    )

    def __str__(self):
        return f"Factura ID: {self.id}"

    class Meta:
        verbose_name = "Factura"
        verbose_name_plural = "Facturas"

class CatalogoBancos(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    nombre = models.CharField(max_length=255, verbose_name="Nombre del Banco")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Banco (Catálogo)"
        verbose_name_plural = "Bancos (Catálogo)"

# Esta es la definición ÚNICA y CORREGIDA de CrowdCaso
class CrowdCaso(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito en Django)
    creador = models.ForeignKey( # Nombre de campo cambiado para convención Django
        CrowdUsuario,
        on_delete=models.CASCADE,
        db_column="creador_id_morelia", # Mapea al nombre de columna SQL
        related_name="casos_creados",
        verbose_name="Creador del Caso (Usuario)"
    )
    exposicion_titulo = models.CharField(max_length=255, verbose_name="Título de la Exposición")
    exposicion_quien_soy = models.TextField(verbose_name="Quién Soy (Exposición)")
    exposicion_que_necesito = models.TextField(verbose_name="Qué Necesito (Exposición)")
    exposicion_porque = models.TextField(verbose_name="Por Qué (Exposición)")
    exposicion_detalles_adicionales = models.TextField(verbose_name="Detalles Adicionales (Exposición)")
    exposicion_promocional = models.TextField(verbose_name="Texto Promocional (Exposición)")
    # Usar FileField para videos e ImageField para imágenes.
    # 'upload_to' especifica un subdirectorio dentro de MEDIA_ROOT.
    video_promocional = models.FileField(upload_to='casos_videos/', null=True, blank=True, verbose_name="Video Promocional")
    imagen_promocional = models.ImageField(upload_to='casos_imagenes/', null=True, blank=True, verbose_name="Imagen Promocional")

    categoria = models.ForeignKey(
        CrowdCategoria,
        on_delete=models.PROTECT, # Si la categoría se borra y tiene casos, se previene el borrado.
        db_column="categoria_id",
        verbose_name="Categoría"
        # null=False es implícito aquí porque on_delete no es SET_NULL y null no se especifica como True
    )

    cantidad_requerida = models.FloatField(verbose_name="Cantidad Requerida")
    cantidad_obtenida = models.FloatField(default=0.0, verbose_name="Cantidad Obtenida")

    estatus = models.ForeignKey(
        CrowdCatalogoEstatus,
        on_delete=models.SET_NULL,
        null=True, blank=True, # Permite nulos como en el SQL original para estatus_id
        db_column="estatus_id",
        verbose_name="Estatus del Caso"
    )
    fecha_publicacion = models.DateField(verbose_name="Fecha de Publicación")
    fecha_creacion = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Creación")
    fecha_fin = models.DateField(verbose_name="Fecha de Fin de Campaña")

    programa_municipal = models.ForeignKey(
        SistemaMunicipalPrograma,
        on_delete=models.SET_NULL,
        null=True, blank=True, # Permite nulos como en el SQL original para municipal_programa_id
        db_column="municipal_programa_id",
        related_name="casos_asociados",
        verbose_name="Programa Municipal Asociado"
    )

    def __str__(self):
        return self.exposicion_titulo

    class Meta:
        verbose_name = "Caso de Crowdfunding"
        verbose_name_plural = "Casos de Crowdfunding"
        ordering = ['-fecha_creacion']

class CrowdCasoArticulo(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.CASCADE,
        db_column="caso_id",
        related_name="articulos",
        verbose_name="Caso Asociado"
    )
    descripcion = models.CharField(max_length=255, verbose_name="Descripción del Artículo")
    recibo_tipo = models.CharField(max_length=255, verbose_name="Tipo de Recibo")
    precio = models.FloatField(verbose_name="Precio del Artículo")

    def __str__(self):
        return f"{self.descripcion} ({self.caso.exposicion_titulo if self.caso else 'Sin caso'})"

    class Meta:
        verbose_name = "Artículo de Caso"
        verbose_name_plural = "Artículos de Casos"

class CrowdReacciones(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    TIPO_INTERACCION_CHOICES = [
        ('L', 'Like'), # Ejemplo, definir los char reales
        ('M', 'Me Encanta'),
        ('A', 'Apoyo'),
        # ... otros tipos de reacción
    ]
    tipo_interaccion = models.CharField(max_length=1, choices=TIPO_INTERACCION_CHOICES, verbose_name="Tipo de Interacción")

    promotor = models.ForeignKey( # Cambiado de promotor_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE, # Si el usuario se borra, sus reacciones también
        db_column="promotor_id_morelia",
        verbose_name="Promotor (Usuario)"
    )
    caso = models.ForeignKey( # Cambiado de caso_id
        CrowdCaso,
        on_delete=models.CASCADE, # Si el caso se borra, sus reacciones también
        db_column="caso_id",
        verbose_name="Caso"
    )
    fecha = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Reacción")

    class Meta:
        verbose_name = "Reacción"
        verbose_name_plural = "Reacciones"
        unique_together = [['promotor', 'caso', 'tipo_interaccion']] # Para evitar reacciones duplicadas del mismo tipo por el mismo usuario al mismo caso

class CrowdSeguidores(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    creador_seguido = models.ForeignKey( # Cambiado de creador_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE,
        related_name="seguidores_set", # El usuario seguido tiene un set de seguidores
        db_column="creador_id_morelia",
        verbose_name="Creador Seguido"
    )
    promotor_seguidor = models.ForeignKey( # Cambiado de promotor_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE,
        related_name="siguiendo_set", # El usuario seguidor tiene un set de usuarios a los que sigue
        db_column="promotor_id_morelia",
        verbose_name="Promotor Seguidor"
    )
    fecha = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Seguimiento")

    class Meta:
        verbose_name = "Seguidor"
        verbose_name_plural = "Seguidores"
        unique_together = [['creador_seguido', 'promotor_seguidor']] # Un usuario no puede seguir al mismo creador múltiples veces

class CrowdProgramaMunicipalBeneficiario(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    beneficiario = models.ForeignKey( # Cambiado de creador_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE, # O PROTECT si el registro de beneficiario es crítico
        db_column="creador_id_morelia",
        verbose_name="Beneficiario (Usuario)"
    )
    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.SET_NULL, # Si el caso se borra, el registro de beneficiario podría quedar huérfano o borrarse (CASCADE)
        null=True, blank=True,
        db_column="caso_id",
        verbose_name="Caso Asociado"
    )
    programa_municipal = models.ForeignKey( # Cambiado de municipal_programa_id
        SistemaMunicipalPrograma,
        on_delete=models.CASCADE, # O PROTECT
        db_column="municipal_programa_id", # SQL dice municipal_programa_id int (no NOT NULL)
        null=True, blank=True, # Hacerlo nullable en Django también
        verbose_name="Programa Municipal"
    )
    fecha = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Registro como Beneficiario")
    # "estatus" char NOT NULL
    ESTATUS_BENEFICIARIO_CHOICES = [
        ('A', 'Aprobado'),
        ('P', 'Pendiente'),
        ('R', 'Rechazado'),
        # ... otros estados
    ]
    estatus = models.CharField(max_length=1, choices=ESTATUS_BENEFICIARIO_CHOICES, verbose_name="Estatus del Beneficiario")

    class Meta:
        verbose_name = "Beneficiario de Programa Municipal"
        verbose_name_plural = "Beneficiarios de Programas Municipales"

class CrowdVotacion(models.Model):
    # "id" float PRIMARY KEY NOT NULL - Django no soporta FloatField como PK. Usaremos BigAutoField o AutoField (entero)
    # Si el ID original es realmente un float y es externo, se podría usar un FloatField con unique=True, y Django usaría su propio PK auto-incremental.
    # Por ahora, asumiré que el ID float es un error en el SQL y usaré el PK automático de Django.
    # Si "id" debe ser un float y es la PK, se requeriría una estrategia diferente (ej. CharField si es un float con formato fijo, o manejarlo manualmente).
    # Voy a ignorar "id float PRIMARY KEY" y usar el AutoField de Django. Si el float es un dato importante, se agrega como otro campo.

    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.CASCADE,
        db_column="caso_id", # SQL dice "caso_id int NOT NULL"
        verbose_name="Caso Votado"
    )
    programa_municipal = models.ForeignKey( # Cambiado de municipal_programa_id
        SistemaMunicipalPrograma,
        on_delete=models.CASCADE, # Si el programa se borra, los votos asociados también
        db_column="municipal_programa_id", # SQL dice "municipal_programa_id int NOT NULL"
        verbose_name="Programa Municipal"
    )
    promotor = models.ForeignKey( # Cambiado de promotor_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE,
        db_column="promotor_id_morelia", # SQL dice "promotor_id_morelia varchar NOT NULL"
        verbose_name="Promotor Votante (Usuario)"
    )
    fecha = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Votación")

    class Meta:
        verbose_name = "Votación"
        verbose_name_plural = "Votaciones"
        # Para que un promotor no vote múltiples veces por el mismo caso en el mismo programa:
        unique_together = [['caso', 'programa_municipal', 'promotor']]


class ReglasOperacion(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    regla = models.TextField(verbose_name="Descripción de la Regla")
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otro'), # O 'Ambos', 'Indistinto'
        ('N', 'No Aplica'), # Si la regla no depende del sexo
    ]
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES, verbose_name="Sexo Aplicable")
    edad_inicio = models.IntegerField(verbose_name="Edad de Inicio Aplicable")
    edad_fin = models.IntegerField(verbose_name="Edad de Fin Aplicable")
    colonia = models.CharField(max_length=255, verbose_name="Colonia Aplicable") # SQL dice char, pero CharField es más flexible

    programa_municipal = models.ForeignKey( # Cambiado de municipal_programa_id
        SistemaMunicipalPrograma,
        on_delete=models.CASCADE, # Si se borra el programa, se borran sus reglas.
        db_column="municipal_programa_id",
        null=True, blank=True, # SQL dice int, no NOT NULL
        related_name="reglas_operacion",
        verbose_name="Programa Municipal"
    )

    def __str__(self):
        return f"Regla para {self.programa_municipal.descripcion_nombre if self.programa_municipal else 'N/A'}: {self.regla[:50]}..."

    class Meta:
        verbose_name = "Regla de Operación"
        verbose_name_plural = "Reglas de Operación"

class CrowdCompromiso(models.Model):
    # "id" int PRIMARY KEY NOT NULL - Django's AutoField will be used by default.
    # If 'id' must be exactly as in SQL (not auto-generated by Django), then:
    # id = models.IntegerField(primary_key=True, verbose_name="ID Compromiso")
    # However, this is unusual if it's not a foreign key itself. Assuming AutoField is fine.

    creador = models.ForeignKey(
        CrowdUsuario,
        on_delete=models.CASCADE,
        related_name='compromisos_creados',
        db_column="creador_id_morelia",
        verbose_name="Creador (Usuario)"
    )
    promotor = models.ForeignKey(
        CrowdUsuario,
        on_delete=models.CASCADE,
        related_name='compromisos_realizados',
        db_column="promotor_id_morelia",
        verbose_name="Promotor (Usuario)"
    )
    programa_social = models.ForeignKey( # Cambiado de programa_social_id
        SistemaMunicipalPrograma,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        db_column="programa_social_id",
        verbose_name="Programa Social Asociado"
    )
    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.CASCADE,
        db_column="caso_id",
        verbose_name="Caso Asociado"
    )
    fecha_creacion = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Creación")
    fecha_compromiso_limite = models.DateField(verbose_name="Fecha Límite del Compromiso")
    fecha_verificacion = models.DateTimeField(null=True, blank=True, verbose_name="Fecha de Verificación") # SQL: timestamp NOT NULL - Django allows null for blank=True

    monto = models.FloatField(verbose_name="Monto del Compromiso")
    monto_abonado = models.FloatField(default=0.0, verbose_name="Monto Abonado")

    agradecimiento_texto = models.TextField(null=True, blank=True, verbose_name="Texto de Agradecimiento")
    agradecimiento_imagen_path = models.TextField(null=True, blank=True, verbose_name="Ruta Imagen Agradecimiento") # Podría ser ImageField
    agradecimiento_video_path = models.TextField(null=True, blank=True, verbose_name="Ruta Video Agradecimiento") # Podría ser FileField

    # "estatus" char NOT NULL
    ESTATUS_COMPROMISO_CHOICES = [
        ('P', 'Pendiente'), # Placeholder
        ('C', 'Cumplido'),
        ('V', 'Vencido'),
        ('A', 'Abonado Parcialmente'),
    ]
    estatus = models.CharField(max_length=1, choices=ESTATUS_COMPROMISO_CHOICES, verbose_name="Estatus del Compromiso")

    # "tipo" char NOT NULL - ej. Donación, Préstamo, Recompensa
    TIPO_COMPROMISO_CHOICES = [
        ('D', 'Donación'), # Placeholder
        ('P', 'Préstamo'),
        ('R', 'Recompensa'),
    ]
    tipo = models.CharField(max_length=1, choices=TIPO_COMPROMISO_CHOICES, verbose_name="Tipo de Compromiso")

    # "origen" char NOT NULL - ej. Directo, Municipal, Empresa
    ORIGEN_COMPROMISO_CHOICES = [
        ('D', 'Directo del Ciudadano'), # Placeholder
        ('M', 'Recurso Municipal'),
        ('E', 'Empresa'),
    ]
    origen = models.CharField(max_length=1, choices=ORIGEN_COMPROMISO_CHOICES, verbose_name="Origen del Compromiso")

    def __str__(self):
        return f"Compromiso ID: {self.id} - Caso: {self.caso.exposicion_titulo if self.caso else 'N/A'}"

    class Meta:
        verbose_name = "Compromiso de Fondeo"
        verbose_name_plural = "Compromisos de Fondeo"

class CrowdCompromisoAbono(models.Model):
    # "id" int PRIMARY KEY NOT NULL - Como arriba, AutoField es lo usual.
    # id = models.IntegerField(primary_key=True, verbose_name="ID Abono") # Si se necesita control explícito

    compromiso = models.ForeignKey(
        CrowdCompromiso,
        on_delete=models.CASCADE, # Si se borra el compromiso, se borran sus abonos
        related_name='abonos',
        db_column="compromiso_id",
        verbose_name="Compromiso Asociado"
    )
    fecha = models.DateTimeField(default=timezone.now, verbose_name="Fecha del Abono")
    # "estatus" char NOT NULL
    ESTATUS_ABONO_CHOICES = [
        ('V', 'Verificado'), # Placeholder
        ('P', 'Pendiente de Verificación'),
        ('R', 'Rechazado'),
    ]
    estatus = models.CharField(max_length=1, choices=ESTATUS_ABONO_CHOICES, verbose_name="Estatus del Abono")
    monto = models.FloatField(verbose_name="Monto del Abono")
    # "tipo_pago" char NOT NULL - ej. Transferencia, Efectivo, Wallet
    TIPO_PAGO_CHOICES = [
        ('T', 'Transferencia Bancaria'), # Placeholder
        ('E', 'Efectivo (Confirmado)'),
        ('W', 'Monedero Interno (si se implementa)'),
    ]
    tipo_pago = models.CharField(max_length=1, choices=TIPO_PAGO_CHOICES, verbose_name="Tipo de Pago")

    def __str__(self):
        return f"Abono de {self.monto} para Compromiso ID: {self.compromiso_id}"

    class Meta:
        verbose_name = "Abono de Compromiso"
        verbose_name_plural = "Abonos de Compromisos"

class CrowdCompromisoEvidencia(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    archivo = models.CharField(max_length=255, verbose_name="Ruta o Nombre del Archivo de Evidencia") # Podría ser FileField/ImageField
    fecha_carga = models.DateTimeField(default=timezone.now, verbose_name="Fecha de Carga")
    promotor = models.ForeignKey(
        CrowdUsuario,
        on_delete=models.CASCADE, # O SET_NULL si la evidencia debe persistir sin usuario
        db_column="promotor_id_morelia",
        verbose_name="Promotor que Carga"
    )
    compromiso = models.ForeignKey(
        CrowdCompromiso,
        on_delete=models.CASCADE, # La evidencia está fuertemente ligada al compromiso
        null=True, blank=True, # SQL dice int, no NOT NULL
        related_name='evidencias',
        db_column="compromiso_id",
        verbose_name="Compromiso Asociado"
    )

    def __str__(self):
        return f"Evidencia para Compromiso ID: {self.compromiso_id} - Archivo: {self.archivo}"

    class Meta:
        verbose_name = "Evidencia de Compromiso"
        verbose_name_plural = "Evidencias de Compromisos"

class CrowdPregunta(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    promotor_pregunta = models.ForeignKey( # Cambiado de promotor_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE, # Si el usuario se borra, sus preguntas también
        related_name='preguntas_realizadas',
        db_column="promotor_id_morelia", # SQL: promotor_id_morelia int NOT NULL -> CrowdUsuario.id_morelia es varchar. Esto es un problema de tipo.
                                        # Asumiré que promotor_id_morelia en esta tabla DEBERÍA ser varchar para coincidir con CrowdUsuario.pk
        verbose_name="Promotor que Pregunta"
    )
    # Ajuste necesario: Si promotor_id_morelia en CrowdPregunta es FK a CrowdUsuario.id_morelia (varchar), el tipo debe coincidir.
    # Django maneja esto automáticamente si el FK es al modelo CrowdUsuario.

    creador_respuesta = models.ForeignKey( # Cambiado de creador_id_morelia
        CrowdUsuario,
        on_delete=models.SET_NULL, # Si el creador se borra, la pregunta puede quedar sin respondedor o la respuesta borrarse.
        null=True, blank=True,
        related_name='preguntas_respondidas',
        db_column="creador_id_morelia", # SQL: creador_id_morelia int -> Mismo problema de tipo que arriba.
        verbose_name="Creador que Responde"
    )
    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.CASCADE, # Las preguntas están ligadas al caso
        db_column="caso_id",
        verbose_name="Caso Relacionado"
    )
    pregunta = models.CharField(max_length=255, verbose_name="Pregunta") # SQL: varchar NOT NULL
    respuesta = models.CharField(max_length=255, null=True, blank=True, verbose_name="Respuesta") # SQL: varchar
    fecha_pregunta = models.DateField(default=datetime.date.today, verbose_name="Fecha de Pregunta") # Corrected default for serialization
    fecha_respuesta = models.DateField(null=True, blank=True, verbose_name="Fecha de Respuesta")

    # "estatus" char NOT NULL
    ESTATUS_PREGUNTA_CHOICES = [
        ('P', 'Pendiente'),
        ('R', 'Respondida'),
        ('O', 'Oculta'), # Ejemplo
    ]
    estatus = models.CharField(max_length=1, choices=ESTATUS_PREGUNTA_CHOICES, verbose_name="Estatus de la Pregunta")

    def __str__(self):
        return f"Pregunta sobre '{self.caso.exposicion_titulo if self.caso else 'N/A'}': {self.pregunta[:50]}..."

    class Meta:
        verbose_name = "Pregunta y Respuesta"
        verbose_name_plural = "Preguntas y Respuestas"

class CrowdSoporteMultimedia(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    archivo_path = models.CharField(max_length=255, null=True, blank=True, verbose_name="Ruta del Archivo Multimedia") # SQL: varchar. Podría ser FileField/ImageField
    fecha_carga = models.DateField(default=datetime.date.today, verbose_name="Fecha de Carga") # Corrected default for serialization

    creador = models.ForeignKey( # Cambiado de creador_id_morelia
        CrowdUsuario,
        on_delete=models.CASCADE,
        db_column="creador_id_morelia", # SQL: creador_id_morelia int NOT NULL -> Mismo problema de tipo.
        verbose_name="Creador (Usuario)"
    )
    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.CASCADE,
        related_name='multimedia_soporte',
        db_column="caso_id", # SQL: caso_id int NOT NULL
        verbose_name="Caso Asociado"
    )

    def __str__(self):
        return f"Multimedia para '{self.caso.exposicion_titulo if self.caso else 'N/A'}': {self.archivo_path}"

    class Meta:
        verbose_name = "Soporte Multimedia"
        verbose_name_plural = "Soportes Multimedia"

class CrowdConfiguracion(models.Model):
    # "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY (implícito)
    clave = models.CharField(max_length=255, unique=True, verbose_name="Clave de Configuración") # unique=True para que la clave sea única
    valor = models.CharField(max_length=255, verbose_name="Valor de Configuración")

    def __str__(self):
        return f"{self.clave}: {self.valor}"

    class Meta:
        verbose_name = "Configuración del Sistema"
        verbose_name_plural = "Configuraciones del Sistema"

class CrowdChat(models.Model):
    # Esta tabla no tiene un PK definido explícitamente en el SQL, lo cual es raro.
    # Django requerirá una PK. Se usará la automática.
    # Las FKs a CrowdUsuario.id_morelia (varchar) son correctas.

    from_usuario = models.ForeignKey( # Cambiado de from_id_morelia
        CrowdUsuario,
        on_delete=models.SET_NULL, # O CASCADE, dependiendo de si se quieren mantener los mensajes si un usuario se va
        null=True,
        related_name='mensajes_enviados',
        db_column="from_id_morelia",
        verbose_name="Remitente"
    )
    to_usuario = models.ForeignKey( # Cambiado de to_id_morelia
        CrowdUsuario,
        on_delete=models.SET_NULL, # Similar a from_usuario
        null=True,
        related_name='mensajes_recibidos',
        db_column="to_id_morelia",
        verbose_name="Destinatario"
    )
    contenido = models.TextField(verbose_name="Contenido del Mensaje")
    caso = models.ForeignKey(
        CrowdCaso,
        on_delete=models.CASCADE, # Los mensajes de chat suelen estar ligados a un contexto (caso)
        db_column="caso_id",
        verbose_name="Caso Relacionado"
    )
    fecha = models.DateTimeField(default=timezone.now, verbose_name="Fecha del Mensaje")

    class Meta:
        verbose_name = "Mensaje de Chat"
        verbose_name_plural = "Mensajes de Chat"
        ordering = ['fecha'] # Ordenar mensajes por fecha

# Fin de la definición de modelos para el MVP.
# Revisar inconsistencias de tipos en FKs (int vs varchar) que se comentaron. Django las maneja bien si el FK es al modelo correcto.
# Por ejemplo, CrowdPregunta.promotor_id_morelia (definido como int en SQL) FK a CrowdUsuario.id_morelia (varchar).
# Django creará la columna FK del tipo de la PK referenciada (varchar en este caso).
