# Generated by Django 5.2.4 on 2025-07-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exposicion_titulo", models.CharField(max_length=255)),
                ("exposicion_quien_soy", models.TextField()),
                ("exposicion_que_necesito", models.TextField()),
                ("exposicion_porque", models.TextField()),
                ("exposicion_detalles_adicionales", models.TextField()),
                ("exposicion_promocional", models.TextField()),
                ("video_promocional", models.TextField(blank=True, null=True)),
                ("imagen_promocional", models.TextField(blank=True, null=True)),
                ("cantidad_requerida", models.FloatField()),
                ("cantidad_obtenida", models.FloatField()),
                ("fecha_publicacion", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CatalogoBancos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogoEstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogoUsuarioTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogoWalletMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=255)),
                ("valor", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datos", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SistemaMunicipalPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_nombre", models.TextField(blank=True, null=True)),
                ("descripcion_detalles", models.TextField(blank=True, null=True)),
                ("presupuesto_total", models.FloatField(blank=True, null=True)),
                ("presupuesto_disponible", models.FloatField(blank=True, null=True)),
                ("presupuesto_meta", models.FloatField(blank=True, null=True)),
                ("estatus", models.CharField(max_length=1)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "cuenta_bancaria",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
                ("icono_path", models.TextField()),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CasoArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("recibo_tipo", models.CharField(max_length=255)),
                ("precio", models.FloatField()),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caso",
            name="estatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crowd.catalogoestatus",
            ),
        ),
        migrations.AddField(
            model_name="caso",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crowd.categoria"
            ),
        ),
        migrations.CreateModel(
            name="Compromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_compromiso_limite", models.DateField()),
                ("fecha_verificacion", models.DateTimeField()),
                ("monto", models.FloatField()),
                ("monto_abonado", models.FloatField()),
                ("agradecimiento_texto", models.TextField(blank=True, null=True)),
                ("agradecimiento_imagen_path", models.TextField(blank=True, null=True)),
                ("agradecimiento_video_path", models.TextField(blank=True, null=True)),
                ("estatus", models.CharField(max_length=1)),
                ("tipo", models.CharField(max_length=1)),
                ("origen", models.CharField(max_length=1)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
                (
                    "programa_social",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.sistemamunicipalprograma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompromisoAbono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estatus", models.CharField(max_length=1)),
                ("monto", models.FloatField()),
                ("tipo_pago", models.CharField(max_length=1)),
                (
                    "compromiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowd.compromiso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReglasOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regla", models.TextField()),
                ("sexo", models.CharField(max_length=1)),
                ("edad_inicio", models.IntegerField()),
                ("edad_fin", models.IntegerField()),
                ("colonia", models.CharField(max_length=1)),
                (
                    "municipal_programa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.sistemamunicipalprograma",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caso",
            name="municipal_programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crowd.sistemamunicipalprograma",
            ),
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id_morelia",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario_tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.catalogousuariotipo",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.usuarionivel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoporteMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_carga", models.DateField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SistemaMunicipalProgramaFondeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.FloatField()),
                ("cuenta_bancaria", models.CharField(max_length=255)),
                ("transaccion", models.CharField(max_length=255)),
                ("codigo_verificacion", models.CharField(max_length=255)),
                ("estatus", models.CharField(max_length=1)),
                ("transaccion_detalle", models.TextField()),
                ("fecha_fondeo", models.DateTimeField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowd.catalogobancos",
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.factura"
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowd.sistemamunicipalprograma",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seguidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguidores",
                        to="crowd.usuario",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siguiendo",
                        to="crowd.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_interaccion",
                    models.CharField(
                        choices=[("L", "Like"), ("M", "Me encanta")], max_length=1
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramaMunicipalBeneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estatus", models.CharField(max_length=1)),
                (
                    "caso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.caso",
                    ),
                ),
                (
                    "municipal_programa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.sistemamunicipalprograma",
                    ),
                ),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=255)),
                ("respuesta", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_pregunta", models.DateField(auto_now_add=True)),
                ("fecha_respuesta", models.DateField(blank=True, null=True)),
                ("estatus", models.CharField(max_length=1)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
                (
                    "creador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preguntas_recibidas",
                        to="crowd.usuario",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_hechas",
                        to="crowd.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="factura",
            name="id_ciudadano",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_recibidas",
                to="crowd.usuario",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="id_empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_emitidas",
                to="crowd.usuario",
            ),
        ),
        migrations.CreateModel(
            name="CompromisoEvidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.CharField(max_length=255)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "compromiso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.compromiso",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.usuario"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compromiso",
            name="creador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compromisos_creados",
                to="crowd.usuario",
            ),
        ),
        migrations.AddField(
            model_name="compromiso",
            name="promotor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compromisos_apoyados",
                to="crowd.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
                (
                    "from_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados",
                        to="crowd.usuario",
                    ),
                ),
                (
                    "to_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_recibidos",
                        to="crowd.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="caso",
            name="creador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="casos_creados",
                to="crowd.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Votacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.caso"
                    ),
                ),
                (
                    "municipal_programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowd.sistemamunicipalprograma",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saldo", models.FloatField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateField(auto_now=True)),
                (
                    "id_morelia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.FloatField(blank=True, null=True)),
                ("origen", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "donacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.compromisoabono",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crowd.catalogowalletmovimiento",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crowd.wallet"
                    ),
                ),
            ],
        ),
    ]
