# Generated by Django 5.2.4 on 2025-07-04 19:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogoBancos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del Banco"),
                ),
            ],
            options={
                "verbose_name": "Banco (Catálogo)",
                "verbose_name_plural": "Bancos (Catálogo)",
            },
        ),
        migrations.CreateModel(
            name="CrowdCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exposicion_titulo",
                    models.CharField(
                        max_length=255, verbose_name="Título de la Exposición"
                    ),
                ),
                (
                    "exposicion_quien_soy",
                    models.TextField(verbose_name="Quién Soy (Exposición)"),
                ),
                (
                    "exposicion_que_necesito",
                    models.TextField(verbose_name="Qué Necesito (Exposición)"),
                ),
                (
                    "exposicion_porque",
                    models.TextField(verbose_name="Por Qué (Exposición)"),
                ),
                (
                    "exposicion_detalles_adicionales",
                    models.TextField(verbose_name="Detalles Adicionales (Exposición)"),
                ),
                (
                    "exposicion_promocional",
                    models.TextField(verbose_name="Texto Promocional (Exposición)"),
                ),
                (
                    "video_promocional",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Video Promocional (URL o Path)",
                    ),
                ),
                (
                    "imagen_promocional",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Imagen Promocional (URL o Path)",
                    ),
                ),
                (
                    "cantidad_requerida",
                    models.FloatField(verbose_name="Cantidad Requerida"),
                ),
                (
                    "cantidad_obtenida",
                    models.FloatField(default=0.0, verbose_name="Cantidad Obtenida"),
                ),
                (
                    "fecha_publicacion",
                    models.DateField(verbose_name="Fecha de Publicación"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin de Campaña")),
            ],
            options={
                "verbose_name": "Caso de Crowdfunding",
                "verbose_name_plural": "Casos de Crowdfunding",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="CrowdCatalogoEstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Estatus",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estatus (Catálogo)",
                "verbose_name_plural": "Estatus (Catálogo)",
            },
        ),
        migrations.CreateModel(
            name="CrowdCatalogoUsuarioTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Tipo de Usuario",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Usuario (Catálogo)",
                "verbose_name_plural": "Tipos de Usuario (Catálogo)",
            },
        ),
        migrations.CreateModel(
            name="CrowdCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Categoría"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Caso",
                "verbose_name_plural": "Categorías de Casos",
            },
        ),
        migrations.CreateModel(
            name="CrowdConfiguracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Clave de Configuración",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        max_length=255, verbose_name="Valor de Configuración"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuraciones del Sistema",
            },
        ),
        migrations.CreateModel(
            name="CrowdUsuarioNivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del Nivel"),
                ),
                ("color", models.CharField(max_length=255, verbose_name="Color")),
                ("icono_path", models.TextField(verbose_name="Ruta del Icono")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Nivel de Usuario",
                "verbose_name_plural": "Niveles de Usuario",
            },
        ),
        migrations.CreateModel(
            name="SistemaMunicipalPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion_nombre",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Nombre Descriptivo del Programa",
                    ),
                ),
                (
                    "descripcion_detalles",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Detalles Descriptivos del Programa",
                    ),
                ),
                (
                    "presupuesto_total",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Presupuesto Total"
                    ),
                ),
                (
                    "presupuesto_disponible",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Presupuesto Disponible"
                    ),
                ),
                (
                    "presupuesto_meta",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Presupuesto Meta"
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("A", "Activo"),
                            ("I", "Inactivo"),
                            ("C", "Completado"),
                            ("P", "Pendiente"),
                        ],
                        max_length=1,
                        verbose_name="Estatus del Programa",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "cuenta_bancaria",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cuenta Bancaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa Municipal",
                "verbose_name_plural": "Programas Municipales",
            },
        ),
        migrations.CreateModel(
            name="CrowdCasoArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=255, verbose_name="Descripción del Artículo"
                    ),
                ),
                (
                    "recibo_tipo",
                    models.CharField(max_length=255, verbose_name="Tipo de Recibo"),
                ),
                ("precio", models.FloatField(verbose_name="Precio del Artículo")),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articulos",
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo de Caso",
                "verbose_name_plural": "Artículos de Casos",
            },
        ),
        migrations.AddField(
            model_name="crowdcaso",
            name="estatus",
            field=models.ForeignKey(
                blank=True,
                db_column="estatus_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nucleo_crowdfunding.crowdcatalogoestatus",
                verbose_name="Estatus del Caso",
            ),
        ),
        migrations.AddField(
            model_name="crowdcaso",
            name="categoria",
            field=models.ForeignKey(
                db_column="categoria_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="nucleo_crowdfunding.crowdcategoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="CrowdCompromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "fecha_compromiso_limite",
                    models.DateField(verbose_name="Fecha Límite del Compromiso"),
                ),
                (
                    "fecha_verificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                ("monto", models.FloatField(verbose_name="Monto del Compromiso")),
                (
                    "monto_abonado",
                    models.FloatField(default=0.0, verbose_name="Monto Abonado"),
                ),
                (
                    "agradecimiento_texto",
                    models.TextField(
                        blank=True, null=True, verbose_name="Texto de Agradecimiento"
                    ),
                ),
                (
                    "agradecimiento_imagen_path",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ruta Imagen Agradecimiento"
                    ),
                ),
                (
                    "agradecimiento_video_path",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ruta Video Agradecimiento"
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("C", "Cumplido"),
                            ("V", "Vencido"),
                            ("A", "Abonado Parcialmente"),
                        ],
                        max_length=1,
                        verbose_name="Estatus del Compromiso",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("D", "Donación"),
                            ("P", "Préstamo"),
                            ("R", "Recompensa"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de Compromiso",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("D", "Directo del Ciudadano"),
                            ("M", "Recurso Municipal"),
                            ("E", "Empresa"),
                        ],
                        max_length=1,
                        verbose_name="Origen del Compromiso",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compromiso de Fondeo",
                "verbose_name_plural": "Compromisos de Fondeo",
            },
        ),
        migrations.CreateModel(
            name="CrowdCompromisoAbono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Abono",
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("V", "Verificado"),
                            ("P", "Pendiente de Verificación"),
                            ("R", "Rechazado"),
                        ],
                        max_length=1,
                        verbose_name="Estatus del Abono",
                    ),
                ),
                ("monto", models.FloatField(verbose_name="Monto del Abono")),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("T", "Transferencia Bancaria"),
                            ("E", "Efectivo (Confirmado)"),
                            ("W", "Monedero Interno (si se implementa)"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de Pago",
                    ),
                ),
                (
                    "compromiso",
                    models.ForeignKey(
                        db_column="compromiso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonos",
                        to="nucleo_crowdfunding.crowdcompromiso",
                        verbose_name="Compromiso Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abono de Compromiso",
                "verbose_name_plural": "Abonos de Compromisos",
            },
        ),
        migrations.CreateModel(
            name="CrowdUsuario",
            fields=[
                (
                    "id_morelia",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID Morelia",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, verbose_name="Correo Electrónico"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=255, verbose_name="Contraseña"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
                (
                    "usuario_tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nucleo_crowdfunding.crowdcatalogousuariotipo",
                        verbose_name="Tipo de Usuario",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nucleo_crowdfunding.crowdusuarionivel",
                        verbose_name="Nivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="CrowdSoporteMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ruta del Archivo Multimedia",
                    ),
                ),
                (
                    "fecha_carga",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de Carga"
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multimedia_soporte",
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Asociado",
                    ),
                ),
                (
                    "creador",
                    models.ForeignKey(
                        db_column="creador_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Creador (Usuario)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soporte Multimedia",
                "verbose_name_plural": "Soportes Multimedia",
            },
        ),
        migrations.CreateModel(
            name="CrowdPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.CharField(max_length=255, verbose_name="Pregunta")),
                (
                    "respuesta",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Respuesta"
                    ),
                ),
                (
                    "fecha_pregunta",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de Pregunta"
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("R", "Respondida"),
                            ("O", "Oculta"),
                        ],
                        max_length=1,
                        verbose_name="Estatus de la Pregunta",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Relacionado",
                    ),
                ),
                (
                    "creador_respuesta",
                    models.ForeignKey(
                        blank=True,
                        db_column="creador_id_morelia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preguntas_respondidas",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Creador que Responde",
                    ),
                ),
                (
                    "promotor_pregunta",
                    models.ForeignKey(
                        db_column="promotor_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_realizadas",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Promotor que Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta y Respuesta",
                "verbose_name_plural": "Preguntas y Respuestas",
            },
        ),
        migrations.CreateModel(
            name="CrowdCompromisoEvidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.CharField(
                        max_length=255,
                        verbose_name="Ruta o Nombre del Archivo de Evidencia",
                    ),
                ),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Carga"
                    ),
                ),
                (
                    "compromiso",
                    models.ForeignKey(
                        blank=True,
                        db_column="compromiso_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="nucleo_crowdfunding.crowdcompromiso",
                        verbose_name="Compromiso Asociado",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        db_column="promotor_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Promotor que Carga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de Compromiso",
                "verbose_name_plural": "Evidencias de Compromisos",
            },
        ),
        migrations.AddField(
            model_name="crowdcompromiso",
            name="creador",
            field=models.ForeignKey(
                db_column="creador_id_morelia",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compromisos_creados",
                to="nucleo_crowdfunding.crowdusuario",
                verbose_name="Creador (Usuario)",
            ),
        ),
        migrations.AddField(
            model_name="crowdcompromiso",
            name="promotor",
            field=models.ForeignKey(
                db_column="promotor_id_morelia",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compromisos_realizados",
                to="nucleo_crowdfunding.crowdusuario",
                verbose_name="Promotor (Usuario)",
            ),
        ),
        migrations.CreateModel(
            name="CrowdChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Contenido del Mensaje")),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Mensaje",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Relacionado",
                    ),
                ),
                (
                    "from_usuario",
                    models.ForeignKey(
                        db_column="from_id_morelia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_enviados",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Remitente",
                    ),
                ),
                (
                    "to_usuario",
                    models.ForeignKey(
                        db_column="to_id_morelia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_recibidos",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["fecha"],
            },
        ),
        migrations.AddField(
            model_name="crowdcaso",
            name="creador",
            field=models.ForeignKey(
                db_column="creador_id_morelia",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="casos_creados",
                to="nucleo_crowdfunding.crowdusuario",
                verbose_name="Creador del Caso (Usuario)",
            ),
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Datos de la Factura"
                    ),
                ),
                (
                    "id_ciudadano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_recibidas",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="ID de Ciudadano (Usuario)",
                    ),
                ),
                (
                    "id_empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_emitidas",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="ID de Empresa (Usuario)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
        migrations.CreateModel(
            name="ReglasOperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regla", models.TextField(verbose_name="Descripción de la Regla")),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "No Aplica"),
                        ],
                        max_length=1,
                        verbose_name="Sexo Aplicable",
                    ),
                ),
                (
                    "edad_inicio",
                    models.IntegerField(verbose_name="Edad de Inicio Aplicable"),
                ),
                ("edad_fin", models.IntegerField(verbose_name="Edad de Fin Aplicable")),
                (
                    "colonia",
                    models.CharField(max_length=255, verbose_name="Colonia Aplicable"),
                ),
                (
                    "programa_municipal",
                    models.ForeignKey(
                        blank=True,
                        db_column="municipal_programa_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_operacion",
                        to="nucleo_crowdfunding.sistemamunicipalprograma",
                        verbose_name="Programa Municipal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Operación",
                "verbose_name_plural": "Reglas de Operación",
            },
        ),
        migrations.CreateModel(
            name="CrowdProgramaMunicipalBeneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro como Beneficiario",
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("A", "Aprobado"),
                            ("P", "Pendiente"),
                            ("R", "Rechazado"),
                        ],
                        max_length=1,
                        verbose_name="Estatus del Beneficiario",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        blank=True,
                        db_column="caso_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Asociado",
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        db_column="creador_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Beneficiario (Usuario)",
                    ),
                ),
                (
                    "programa_municipal",
                    models.ForeignKey(
                        blank=True,
                        db_column="municipal_programa_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.sistemamunicipalprograma",
                        verbose_name="Programa Municipal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiario de Programa Municipal",
                "verbose_name_plural": "Beneficiarios de Programas Municipales",
            },
        ),
        migrations.AddField(
            model_name="crowdcompromiso",
            name="programa_social",
            field=models.ForeignKey(
                blank=True,
                db_column="programa_social_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nucleo_crowdfunding.sistemamunicipalprograma",
                verbose_name="Programa Social Asociado",
            ),
        ),
        migrations.AddField(
            model_name="crowdcaso",
            name="programa_municipal",
            field=models.ForeignKey(
                blank=True,
                db_column="municipal_programa_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="casos_asociados",
                to="nucleo_crowdfunding.sistemamunicipalprograma",
                verbose_name="Programa Municipal Asociado",
            ),
        ),
        migrations.CreateModel(
            name="CrowdSeguidores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Seguimiento",
                    ),
                ),
                (
                    "creador_seguido",
                    models.ForeignKey(
                        db_column="creador_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguidores_set",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Creador Seguido",
                    ),
                ),
                (
                    "promotor_seguidor",
                    models.ForeignKey(
                        db_column="promotor_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siguiendo_set",
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Promotor Seguidor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguidor",
                "verbose_name_plural": "Seguidores",
                "unique_together": {("creador_seguido", "promotor_seguidor")},
            },
        ),
        migrations.CreateModel(
            name="CrowdReacciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_interaccion",
                    models.CharField(
                        choices=[("L", "Like"), ("M", "Me Encanta"), ("A", "Apoyo")],
                        max_length=1,
                        verbose_name="Tipo de Interacción",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Reacción",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        db_column="promotor_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Promotor (Usuario)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reacción",
                "verbose_name_plural": "Reacciones",
                "unique_together": {("promotor", "caso", "tipo_interaccion")},
            },
        ),
        migrations.CreateModel(
            name="CrowdVotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Votación",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        db_column="caso_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdcaso",
                        verbose_name="Caso Votado",
                    ),
                ),
                (
                    "promotor",
                    models.ForeignKey(
                        db_column="promotor_id_morelia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.crowdusuario",
                        verbose_name="Promotor Votante (Usuario)",
                    ),
                ),
                (
                    "programa_municipal",
                    models.ForeignKey(
                        db_column="municipal_programa_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo_crowdfunding.sistemamunicipalprograma",
                        verbose_name="Programa Municipal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votación",
                "verbose_name_plural": "Votaciones",
                "unique_together": {("caso", "programa_municipal", "promotor")},
            },
        ),
    ]
