# Generated by Django 5.2.4 on 2025-07-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo_crowdfunding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crowdcaso",
            name="imagen_promocional",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="casos_imagenes/",
                verbose_name="Imagen Promocional",
            ),
        ),
        migrations.AlterField(
            model_name="crowdcaso",
            name="video_promocional",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="casos_videos/",
                verbose_name="Video Promocional",
            ),
        ),
    ]
